version: "3.9"

networks:
  adempiere-backend:

volumes:
  pgdata:

services:
  adempiere.db:
    image: solopcloud/adempiere-postgres:14-experimental-1.0.5
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=adempiere
      - DB_NAME=adempiere
      - ADEMPIERE_PASSWORD=adempiere
    networks:
      - adempiere-backend

  adempiere.backend:
    image: solopcloud/adempiere-backend
    ports:
      - "50059:50059"
    env_file:
      - ./backend.env
    depends_on:
      - adempiere.db
    networks:
      - adempiere-backend
