# This workflow will build a Java project with Gradle
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Project

on:
  release:
    types:
      - created

jobs:

  # Build dist application adempiere-grpc-server
  build-app:
    name: Build dist ADempiere gRPC Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 17
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0 # current

      - name: Set Version Properties
        run: |
          echo "MAIN_VERSION=${{ github.event.release.name }}" >> src/main/java/org/spin/base/version.properties
          echo "DATE_VERSION=$(date +'%Y-%m-%d')" >> src/main/java/org/spin/base/version.properties
          echo "IMPLEMENTATION_VERSION=${{ github.event.release.tag_name }}" >> src/main/java/org/spin/base/version.properties

      - name: Run Create Release
        run: gradle createRelease --warning-mode all --stacktrace
        env:
          GITHUB_DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          GITHUB_DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Upload descriptor file artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-grpc-server.dsc
          path: build/descriptors/adempiere-grpc-server.dsc
          retention-days: 1

      - name: Upload envoy file artifact
        uses: actions/upload-artifact@v4
        with:
          name: envoy.yaml
          path: resources/envoy.yaml
          retention-days: 1

      - name: Upload dist app zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-grpc-server.zip
          path: build/release/adempiere-grpc-server.zip
          retention-days: 1

      - name: Upload dist app zip.MD5 artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-grpc-server.zip.MD5
          path: build/release/adempiere-grpc-server.zip.MD5
          retention-days: 1

      - name: Upload dist app tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-grpc-server.tar
          path: build/release/adempiere-grpc-server.tar
          retention-days: 1

      - name: Upload dist app tar.MD5 artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-grpc-server.tar.MD5
          path: build/release/adempiere-grpc-server.tar.MD5
          retention-days: 1


  publish-binaries:
    name: Upload Binaries adempiere-grpc-server
    needs: build-app
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload Descriptor
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adempiere-grpc-server.dsc/adempiere-grpc-server.dsc

      - name: Upload Envoy config
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: envoy.yaml/envoy.yaml

      - name: Upload zip
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adempiere-grpc-server.zip/adempiere-grpc-server.zip

      - name: Upload zip.MD5
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adempiere-grpc-server.zip.MD5/adempiere-grpc-server.zip.MD5

      - name: Upload tar
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adempiere-grpc-server.tar/adempiere-grpc-server.tar

      - name: Upload tar.MD5
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adempiere-grpc-server.tar.MD5/adempiere-grpc-server.tar.MD5


  # Check secrets to push image in docker hub registry
  check-docker-secrets:
    name: Check if the registry information was set on secrets and variables
    needs:
      - build-app
    runs-on: ubuntu-latest
    outputs:
      is_have_secrets: ${{ steps.check_docker_hub_secrets_job.outputs.is_have_secrets }}
    steps:
      - id: check_docker_hub_secrets_job
        run: |
          if [[ "${{ vars.DOCKER_REGISTRY }}" != "" && \
                "${{ vars.DOCKER_REPO }}" != "" && \
                "${{ secrets.DOCKER_USERNAME }}" != "" && \
                "${{ secrets.DOCKER_TOKEN }}" != "" ]]; \
          then
            echo "Secrets to use a container registry are configured in the repo"
            echo "is_have_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "Secrets to use a container registry were not configured in the repo"
            echo "is_have_secrets=false" >> $GITHUB_OUTPUT
          fi

  # TODO: Download .tar and add docker image without uncompress
  # Publish docker alpine image in Docker Hub Registry to application
  push-alpine-imame-dhr:
    name: Push docker alpine image to Docker Hub
    needs:
      - check-docker-secrets
    # Skip step based on secret
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download build dist app
        uses: actions/download-artifact@v4
        with:
          name: adempiere-grpc-server.zip

      - name: Unzip Asset
        run: |
          unzip adempiere-grpc-server.zip -d docker/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Alpine Tags
        id: set_tags_alpine
        run: |
          # Get the release type
          IS_PRE_RELEASE=${{ github.event.release.prerelease }}
          # Set the base tags, always include the specific version tag
          TAGS="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO }}:${{ github.event.release.tag_name }}-alpine"
          # If it's not a pre-release, add the "latest" tag
          if [[ "$IS_PRE_RELEASE" == "false" ]]; then
            TAGS+=",${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO }}:alpine"
          fi
          # Set the output variable for the next step to use
          echo "tags_to_push=$TAGS" >> $GITHUB_OUTPUT

      - name: Push alpine image in Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpine.Dockerfile
          push: true
          tags: ${{ steps.set_tags_alpine.outputs.tags_to_push }}

  # TODO: Download .tar and add docker image without uncompress
  # Publish docker image multiplatform in Docker Hub Registry to application
  push-imame-dhr:
    name: Push docker image to Docker Hub
    needs:
      - check-docker-secrets
    # Skip step based on secret
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download build dist app
        uses: actions/download-artifact@v4
        with:
          name: adempiere-grpc-server.zip

      - name: Unzip Asset
        run: |
          unzip adempiere-grpc-server.zip -d docker/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Tags
        id: set_tags
        run: |
          # Get the release type
          IS_PRE_RELEASE=${{ github.event.release.prerelease }}
          # Set the base tags, always include the specific version tag
          TAGS="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO }}:${{ github.event.release.tag_name }}"
          # If it's not a pre-release, add the "latest" tag
          if [[ "$IS_PRE_RELEASE" == "false" ]]; then
            TAGS+=",${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO }}:latest"
          fi
          # Set the output variable for the next step to use
          echo "tags_to_push=$TAGS" >> $GITHUB_OUTPUT

      - name: Push image in Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/ubuntu.Dockerfile
          platforms: linux/amd64,linux/amd64/v2
          # platforms: linux/amd64,linux/amd64/v2,linux/arm64/v8
          push: true
          tags: ${{ steps.set_tags.outputs.tags_to_push }}


  # Publish docker image multiplatform in Docker Hub Registry to application
  push-grpc-proxy-imame-dhr:
    name: Push grpc-proxy docker image to Docker Hub
    needs:
      - check-docker-secrets
    # Skip step based on secret
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download build dist app
        uses: actions/download-artifact@v4
        with:
          name: adempiere-grpc-server.dsc
          path: docker/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Tags
        id: set_envoy_tags
        run: |
          # Get the release type
          IS_PRE_RELEASE=${{ github.event.release.prerelease }}
          # Set the base tags, always include the specific version tag
          TAGS="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO_PROXY }}:${{ github.event.release.tag_name }}"
          # If it's not a pre-release, add the "latest" tag
          if [[ "$IS_PRE_RELEASE" == "false" ]]; then
            TAGS+=",${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO_PROXY }}:latest"
          fi
          # Set the output variable for the next step to use
          echo "tags_to_push=$TAGS" >> $GITHUB_OUTPUT

      - name: Push image in Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/grpc_proxy.Dockerfile
          platforms: linux/amd64,linux/amd64/v2,linux/arm64/v8
          push: true
          tags: ${{ steps.set_envoy_tags.outputs.tags_to_push }}
