# This workflow will build a Java project with Gradle
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Push Main Branches

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - develop
      - experimental
      - main
      - master
      - action-**
      - test**

jobs:

  # Build dist application backend
  build-app:
    name: Build dist backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 11
          architecture: x64

      - name: Build with Gradle
        run: gradle createRelease

      - name: Upload dist app zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend.zip
          path: build/release/backend.zip


  # Publish container image in Docker Hub registry to application
  push-imame-dhr:
    name: Push Docker image to Docker Hub
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download build dist app
        uses: actions/download-artifact@v3
        with:
          name: backend.zip
          path: dist

      - name: Unzip dist file
        run: |
          cd dist
          unzip -o backend.zip

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v2
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Lower Case to owner and repository
        run: |
          ORG=$OWNER
          if [ -n "${{ secrets.DOCKERHUB_ORG }}" ]; then
            echo "Set secret DOCKERHUB_ORG as namespace"
            ORG=${{ secrets.DOCKERHUB_ORG }}
          else
            echo "Set OWNER ($OWNER) as namespace "
          fi
          echo "ORG_LC=${ORG,,}" >> ${GITHUB_ENV}
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
          echo "REPO_LC=${NAME,,}" >> ${GITHUB_ENV}
        env:
          # to docker image namespace
          OWNER: '${{ github.repository_owner }}'
          NAME: '${{ github.event.repository.name }}'

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Push image in Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build-docker/Dockerfile.prod
          push: true
          tags: |
            ${{ env.ORG_LC }}/${{ env.REPO_LC }}:latest
            ${{ env.ORG_LC }}/${{ env.REPO_LC }}:${{ github.sha }}
            ${{ env.ORG_LC }}/${{ env.REPO_LC }}:${{ steps.branch-name.outputs.current_branch }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
